apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  namespace: teko3 # Replace with your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: nophramel/transfer_arbeit:latest # image from my dockerhub?
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: REDIS_HOST
              value: redis-service
          ports:
            - containerPort: 3000